apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-publish
spec:
  description: This task will build and push an image using Docker.
  params:
  - name: image
    description: Name of the image Docker will produce.
  - name: dockerfile
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: context
    description: Path to the directory to use as context.
    default: .
  - name: docker-credentials-secret
    description: Secret name containing username and password for login on Docker Hub.
    default: docker-credentials
  workspaces:
  - name: source
  steps:
  - name: docker-build
    image: docker
    workingDir: $(workspaces.source.path)
    script: docker build --no-cache -f $(params.dockerfile) -t $(params.image) $(params.context)
    volumeMounts:
    - mountPath: /var/run/
      name: dind-socket
  - name: docker-login
    image: docker
    workingDir: $(workspaces.source.path)
    script: docker login -u $USERNAME -p $TOKEN
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: docker-credentials
          key: username
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: docker-credentials
          key: password
    volumeMounts:
    - mountPath: /var/run/
      name: dind-socket
  - name: docker-push
    image: docker
    workingDir: $(workspaces.source.path)
    script: docker push $(params.image)
    volumeMounts:
    - mountPath: /var/run/
      name: dind-socket

  sidecars:
  - image: docker:dind
    name: server
    securityContext:
      privileged: true
    readinessProbe:
      periodSeconds: 1
      exec:
        command: ['docker', 'ps']
    volumeMounts:
    - mountPath: /var/lib/docker
      name: dind-storage
    - mountPath: /var/run/
      name: dind-socket

  volumes:
  - name: dind-storage
    emptyDir: {}
  - name: dind-socket
    emptyDir: {}
