apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  annotations:
    tekton.dev/docker-0: https://hub.docker.com
type: kubernetes.io/basic-auth
stringData:
  username: crix128
  password: <token>
