apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: main-pipeline
spec:
  resources:
    - name: my-repo
      type: git
    - name: my-image
      type: image
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
    - name: build-publish-app
      taskRef:
        name: docker-build
      runAfter:
        - clone-repo
#    - name: deploy-app
#      taskRef:
#        name: docker-deploy
#      runAfter:
#        - clone-repo
